name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"


      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install --save-dev -g newman@^5.1.2
          npm install -g newman-reporter-htmlextra


      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults


      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run petstore.postman_collection.json -r cli,htmlextra --reporter-htmlextra-export testResults/htmlreport.html
          
      # Run Newman htmlextra image
      - name: Build the project
        run: |
          echo Start to build,
          docker container run -t -v $(pwd):/etc/newman dannydainton/htmlextra \
          run 'petstore.postman_collection.json' \
          -k \
          -r cli,htmlextra \
          --reporter-htmlextra-export /etc/newman/docs/index.html \
          --reporter-htmlextra-browserTitle "QA Newman" \
          --reporter-htmlextra-title "QA Newman - HTMLEXTRA, GitHub Actions e GitHub Pages"
      # Show the directory and list its contents
      - name: List workdir
        run:  ls -lathr ./docs

      # Publish report on the github pages
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir : ./docs


      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
