name: Project test & build

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          
      - name: Install newman
        run: |
          npm install --save-dev -g newman@^5.1.2
          npm install -g newman-reporter-htmlextra
          
      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: |
          newman run petstore.postman_collection.json -r cli,htmlextra --reporter-htmlextra-export testResults/htmlreport.html
          
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults

      - name: Build 👷
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          # в значение GITHUB_TOKEN помещается ссылка на ваш секрет в репозитории
          # в данном случае его название KEY
          GITHUB_TOKEN: ${{ secrets.my_tok }}
          BRANCH: gh-pages
          FOLDER: testResults/htmlreport.html
          CLEAN: true
